# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7920779b619eb6c94850df99169cd94304c5e1c19406a40fed8192a6bd88f66152c2553589159f3b7b7705ad6ea5dda83237587e2747ef7a47d37d68080a2522

test:
  secret_key_base: 1b6d1f25b23b80c7de7ad33100ed96e681dcf467a8c2ccd8f73795e2465ed650531a500218b9b45e97862167fe4615b783b16d922aaecf2828519c41ae8b63ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
